### ISSUE TITLE
Why is Clear NuGet Cache &c grayed out?

### ISSUE THREAD

**Issue by SmatchyLaPaglia** [yuv4ik/vsmacdeepclean#7]
Installing to try to get rid of the MissingMethodException bug as referenced here: https://stackoverflow.com/questions/40278762/xamarin-forms-xamlcompilation-missingmethodexception/

Why can't I select the Clear NuGet Cache or any of the other options on the same menu?

**Comment by yuv4ik** [comment]
> Why can't I select the Clear NuGet Cache or any of the other options on the same menu?
All the three options are grayed out?

- Clear NuGet Cache
- Clear Android Library Cache
- Clear Unused Framework Libraries

Sounds weird, however, most of the commands depends on specific directories and if they does not exists the commands are disabled. Please check the commands and their `Update` method which defines if the command is enabled or disabled. You could also check the output log for more information.

As for your issue, you may need the `Clear NuGet Packages` on the project level and not in the global cache.

**Comment by SmatchyLaPaglia** [comment]
Thanks for the tip--it was the opposite actually, I had to do it from the main launch screen and not the project level.

And yes, all three were gray, and all three came back once I went to the launch screen.

**Comment by yuv4ik** [comment]
Good to hear that the problem is resolved.
