### ISSUE TITLE
Not working with VS2019 for mac

### ISSUE THREAD

**Issue by engmsaleh** [yuv4ik/vsmacdeepclean#8]

**Comment by yuv4ik** [comment]
Could you please provide a bit more details?

**Comment by engmsaleh** [comment]
I have tried to install it on **VS2019**, here is the error I got
![Screen Shot 2019-04-18 at 4 36 56 PM](https://user-images.githubusercontent.com/462150/56368697-43df4480-61f8-11e9-94f6-75574876d4cf.png)

**Comment by yuv4ik** [comment]
I will look into it, however, that may take time.

Thanks for your report.

**Comment by yuv4ik** [comment]
Fixed by #9 .
